## Test file to be merged with values.yaml.
##
## Set all "create" flags to true to exhaust as many config options as possible.
##
global:
  labels:
    foo: bar
  annotations:
    foo.com/bar: baz

strongdm:
  auth:
    adminToken: foo.bar.baz
  serviceAccount:
    create: true
  discoveryUsername: sdm-discovery
  healthcheckUsername: sdm-healthchecks
  autoRegisterCluster:
    enabled: true
    identitySet: i-abcd1234
  config:
    additionalEnvVars:
      foo: bar
      bar: 2
      baz: false
