name: Helm Unit Tests (sdm-proxy)

on:
  pull_request:
    branches: [main]
    paths:
      - 'deployments/**'
      - '.github/workflows/helm-unittest.yml'

jobs:
  helm-unittest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.16.3'
      
      - name: Install helm unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest
      
      - name: Run helm unittest for sdm-proxy
        run: |
          cd deployments/sdm-proxy
          helm unittest .
      
    #   - name: Upload test results
    #     uses: actions/upload-artifact@v4
    #     if: always()
    #     with:
    #       name: helm-unittest-results
    #       path: deployments/sdm-proxy/tests/__snapshot__/ 