name: Test CLI as root gocimg

on:
  workflow_dispatch

jobs:
  test-cli:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Install StrongDM CLI Client
      env:
        SDM_ADMIN_TOKEN: ${{ secrets.SDM_SERVICE_ACCOUNT_TOKEN }}
      run: |
        # Install dependencies and download StrongDM CLI
        sudo apt-get update && sudo apt-get -y install curl unzip
        curl -J -O -L https://app.strongdm.com/releases/cli/linux
        unzip sdmcli_*.zip
        
        # Create unprivileged user for SDM operations  
        sudo useradd -m -s /bin/bash circleci
        echo "beginning install"
        # Install as root but configure for sdmuser
        sudo ./sdm install --app-domain app.strongdm.com --admin-token "$SDM_ADMIN_TOKEN" --nostart --user circleci

        
        # Switch to unprivileged user for all SDM operations
        sudo -u circleci sdm login --admin-token "$SDM_ADMIN_TOKEN"
        sudo -u circleci sdm listen --daemon &
        sleep 15
        sudo -u circleci sdm status
        sudo -u circleci sdm doctor -v
