name: Test CLI as root

on:
  workflow_dispatch

jobs:
  test-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Install StrongDM CLI Client
      run: |
        # Download and install StrongDM CLI
        curl -J -O -L https://app.strongdm.com/releases/cli/linux
        sudo apt -y install unzip
        unzip sdmcli_*.zip
        export SDM_ADMIN_TOKEN=${{ secrets.SDM_ADMIN_TOKEN }}
        sudo ./sdm install --app-domain app.strongdm.com --admin-token $SDM_ADMIN_TOKEN --nostart
        sudo sdm login --admin-token "${SDM_ADMIN_TOKEN}"
