name: Test CLI as root gocimg

on:
  workflow_dispatch

jobs:
  test-cli:
    runs-on: ubuntu-latest
    environment: dev
    container:
      image: cimg/go:1.24.5

    steps:
    - name: Install StrongDM CLI Client
      env:
        SDM_ADMIN_TOKEN: ${{ secrets.SDM_SERVICE_ACCOUNT_TOKEN }}
        HOME: "/home/circleci"
        SDM_HOME: "/home/circleci"
      run: |
        # Install dependencies and download StrongDM CLI
        sudo apt-get update && sudo apt-get -y install curl unzip
        curl -J -O -L https://app.strongdm.com/releases/cli/linux
        unzip sdmcli_*.zip
        
        echo "beginning install"
        # Install as root but configure for sdmuser
        sudo env SDM_HOME="/home/circleci/.sdm" ./sdm install --app-domain app.strongdm.com --admin-token "${SDM_ADMIN_TOKEN}" --nostart --user circleci --home /home/circleci
        # Switch to unprivileged user for all SDM operations  
        sudo -u circleci env SDM_HOME="/home/circleci/.sdm" sdm login --admin-token "$SDM_ADMIN_TOKEN"
        sudo -u circleci env SDM_HOME="/home/circleci/.sdm" sdm listen --daemon &
        sleep 15
        sudo -u circleci env SDM_HOME="/home/circleci/.sdm" sdm status
        sudo -u circleci env SDM_HOME="/home/circleci/.sdm" sdm doctor -v
