name: Test CLI as root gocimg

on:
  workflow_dispatch

jobs:
  test-cli:
    runs-on: ubuntu-latest
    environment: dev
    container:
      image: cimg/go:1.24.5

    steps:
    - name: Run StrongDM CLI Client
      env:
        SDM_ADMIN_TOKEN: ${{ secrets.SDM_SERVICE_ACCOUNT_TOKEN }}
        HOME: "/home/circleci"
        SDM_HOME: "/home/circleci/.sdm"
      run: |
        # Install dependencies and download StrongDM CLI
        sudo apt-get update && sudo apt-get -y install curl unzip
        curl -J -O -L https://app.strongdm.com/releases/cli/linux
        unzip sdmcli_*.zip
        export SDM_HOME=/home/circleci/.sdm
        export SDM_ADMIN_TOKEN="${SDM_ADMIN_TOKEN}"
        export SDM_VERBOSE=true
        mkdir -p $SDM_HOME
        sudo chown circleci:circleci $SDM_HOME
        # Switch to unprivileged user for all SDM operations  
        ./sdm login --admin-token "$SDM_ADMIN_TOKEN"
        ./sdm listen --daemon &
        sleep 15
        ./sdm status
        ./sdm doctor -v
