name: Test CLI as root

on:
  workflow_dispatch

jobs:
  test-cli:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --user root

    steps:
    - name: Install StrongDM CLI Client
      run: |
        # Install dependencies and download StrongDM CLI
        apt update && apt -y install curl unzip
        curl -J -O -L https://app.strongdm.com/releases/cli/linux
        unzip sdmcli_*.zip
        export SDM_ADMIN_TOKEN=${{ secrets.SDM_ADMIN_TOKEN }}
        export SDM_APP_DOMAIN="app.strongdm.com"
        ./sdm install --app-domain app.strongdm.com --admin-token $SDM_ADMIN_TOKEN --nostart --user root
        sdm login --admin-token $SDM_ADMIN_TOKEN
