name: Test CLI as root

on:
  workflow_dispatch

jobs:
  test-cli:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install StrongDM CLI Client
      run: |
        # Download and install StrongDM CLI
        curl -J -O -L https://app.strongdm.com/releases/cli/linux
        sudo apt -y install unzip
        unzip sdmcli_*.zip
        sudo ./sdm install --app-domain app.strongdm.com --admin-token "${{ secrets.SDM_ADMIN_TOKEN }}" --user root --nostart
        export SDM_ADMIN_TOKEN=${{ secrets.SDM_ADMIN_TOKEN }}
        sudo sdm login --admin-token $SDM_ADMIN_TOKEN
